In [1]:
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 張量版與純量版內積運算速度比較

import numpy as np
import time

op_num = 500000000
a = np.random.rand(op_num)     # 產生一億個亂數
b = np.random.rand(op_num)     # 產生一億個亂數

c = 0
start = time.time()    # 運算開始時間
c = np.dot(a,b)        # NumPy 張量版內積運算
stop = time.time()     # 運算結束時間
print("張量版內積運算結果:", c)
print("張量版內積運算執行時間:" + str(1000*(stop-start)) + "ms")

c = 0
start = time.time()    # 運算開始時間
for i in range(op_num):
    c += a[i]*b[i]     # Python 純量版內積運算
stop = time.time()     # 運算結束時間
print("純量版內積運算結果:", c)
print("純量版內積運算執行時間:" + str(1000*(stop-start)) + "ms")


張量版內積運算結果: 125005678.94149594
張量版內積運算執行時間:166638.503074646ms
純量版內積運算結果: 125005678.94160321
純量版內積運算執行時間:595186.5057945251ms


In [2]:
# encoding=utf-8
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 純量, 向量, 矩陣, 張量

# 使用 NumPy 套件
import numpy as np

s = 123                             # 建立純量 (scalar)
v1 = [1, 2, 3]                      # 建立向量(vector)
v2 = np.array([4, 5, 6])            # 用 NumPy 建立向量(vector)
m1 = np.array([[5,7,6],             # 用 NumPy 建立矩陣(matrix)
               [3,5,6]])                                      
t1 = np.array([[[1,2],              # 用 NumPy 建立張量(tensor)
                [3,4]],
               [[5,6],
                [7,8]]])    
print("純量: ", s)
print("Python向量: ", v1)
print("NumPy向量: ", v2)
print("NumPy矩陣:\n", m1)
print("NumPy張量:\n", t1)


純量:  123
Python向量:  [1, 2, 3]
NumPy向量:  [4 5 6]
NumPy矩陣:
 [[5 7 6]
 [3 5 6]]
NumPy張量:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# encoding=utf-8
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 矩陣加減乘除 (對應元素加減乘除)

# 使用 NumPy 套件
import numpy as np

X = np.array([[2,4],[6,8]])
Y = np.array([[3,2],[1,4]])


print(np.add(X,Y))            # 矩陣加法 
print(np.subtract(X,Y))       # 矩陣減法 
print(np.multiply(X,Y))       # 矩陣乘法 
print(np.divide(X,Y))         # 矩陣除法


[[ 5  6]
 [ 7 12]]
[[-1  2]
 [ 5  4]]
[[ 6  8]
 [ 6 32]]
[[0.66666667 2.        ]
 [6.         2.        ]]


In [5]:
# encoding=utf-8
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 轉置矩陣

# 使用 NumPy 套件
import numpy as np

a = np.array([[3,7,6,5],             # 用 NumPy 建立矩陣(matrix)
              [2,4,6,8]])        
                              
at = np.transpose(a)               #  np.transpose() -> 轉置矩陣

print('原矩陣 A 為:\n',a)
print('矩陣 A 的轉置矩陣為:\n',at)


原矩陣 A 為:
 [[3 7 6 5]
 [2 4 6 8]]
矩陣 A 的轉置矩陣為:
 [[3 2]
 [7 4]
 [6 6]
 [5 8]]


In [10]:
# encoding=utf-8
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 矩陣維度(形狀)改變

# 使用 NumPy 套件
import numpy as np

X = np.array([[4,5,6],
            [2,4,6],
            [1,3,5],
            [6,8,10]])

print(X)                            # 一維向量


print(np.reshape(X, (12,1)))        # 改成 12 x 1 矩陣


[[ 4  5  6]
 [ 2  4  6]
 [ 1  3  5]
 [ 6  8 10]]
[[ 4]
 [ 5]
 [ 6]
 [ 2]
 [ 4]
 [ 6]
 [ 1]
 [ 3]
 [ 5]
 [ 6]
 [ 8]
 [10]]


In [13]:
# encoding=utf-8
# Programmer: 黃駿瑜
# Date: 2020/5/19
# 線性代數: 矩陣內積 inner product

# 使用 NumPy 套件

import numpy as np

A = np.array([[4,5,6],
            [2,4,6],
            [1,3,5]])
B = np.array([[3,7,5],
            [6,7,8],
            [2,11,4]])

C = np.dot(A, B)              # 向量內積 第2種寫法
print('內積結果為:\n',C)


內積結果為:
 [[ 54 129  84]
 [ 42 108  66]
 [ 31  83  49]]
